name: Update JW Videos Gist

on:
  # Runs every day at 2:00 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install necessary Python libraries
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run your Python script to generate the JSON
      # This step now creates the file instead of updating the Gist directly
      - name: Run Python script to create JSON file
        run: python update_gist.py

      # Step 5: **THE NEW, WORKING ACTION**
      # This action reads the generated file and updates the Gist
      - name: Update Gist
        uses: dineshsonachalam/update-gist@v2.2
        with:
          gist_token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: videos.json # The local file to upload from
    
    print(f"Success! File '{OUTPUT_FILENAME}' created locally.")

if __name__ == "__main__":
    main()
