name: Update JW Videos Gist

on:
  schedule:
    - cron: '0 2 * * *' # Se ejecuta cada día a las 2:00 AM UTC
  workflow_dispatch: # Permite la ejecución manual

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script para obtener vídeos y actualizar Gist
        run: python update_gist.py
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
