name: Update JW Videos Gist

on:
  # Runs every day at 2:00 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install necessary Python libraries
      - name: Install dependencies
        run: pip install requests

      # Step 4: Run your Python script to generate the JSON
      - name: Run Python script
        run: python update_gist.py
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 5: **THE CORRECTED ACTION**
      # Use a working action to update the Gist
      - name: Update Gist
        uses: Amatch/actions-gist@v1.1.0 # This is the new, working action
        with:
          gist_id: ${{ secrets.GIST_ID }}
          file_name: videos.json # The name of the file in your Gist
          content_from_file: videos.json # The local file to upload
          auth_token: ${{ secrets.GH_TOKEN }}
