name: Actualizar Videos JW

on:
  schedule:
    # Se ejecuta todos los días a las 5 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar jwlib
        run: pip install jwlib

      - name: Ejecutar el buscador
        run: python buscador.py

      - name: Actualizar el Gist
        uses: exuanbo/actions-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: videos.json
